# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Gangmuk Lim
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
url: "https://gangmuk.github.io" # the base hostname & protocol for the site
baseurl: ""
photourl: "/assets/img/photos"
og_image: /assets/img/gangmuk.png
google_analytics: "UA-83979019-1"





header:
  pages:
    - name: Home
      slug: /
    - name: Photos
      # slug: /photos
    - name: Blog
      slug: /blog
    - name: Notes
      slug: /notes

footer:
  show_powered_by: false
#  contact:
#    - name: Email
#      value: yourmail@domain.com
#      link: mailto:yourmail@domain.com
#    - name: WeChat
#      value: YourWeChatUsername
#      link: "#"
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/gangmuk
    - name: GitHub
      link: http://github.com/gangmuk
#    - name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@YourTwitterUsername"
#    - name: Facebook
#      link: http://facebook.com/YourFacebookUsername
#    - name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - name: RSS
#      link: /feed.xml

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _posts/unpublished/

# Used for defeating caching
version: 1
